name: Building docker images to run challenge locally

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build for PHP
        run: docker build --target php . -t aurelijusbanelis/callenge:php
      - name: Build for JavaScript
        run: docker build --target js . -t aurelijusbanelis/callenge:js
      - name: Build for Go
        run: docker build --target go . -t aurelijusbanelis/callenge:go
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: aurelijuschallengebot
          password: ${{ secrets.DOCKERHUB_TOKEN_CHALLENGE_BOT }}
      - name: Pushing latest images
        if: github.event_name == 'push'
        run: |
          docker push aurelijusbanelis/callenge:php
          docker push aurelijusbanelis/callenge:js
          docker push aurelijusbanelis/callenge:go
