name: Run tests

on:
  pull_request:
    paths:
      - 'php/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: LANGUAGE=php go test -v ./... -count 1

      - name: Benchmark
        run: LANGUAGE=php go test -bench=. -benchtime=10s
