name: Run tests

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - ready_for_review
      - reopened
    paths:
      - 'go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request_target.head.ref}}
          repository: ${{github.event.pull_request_target.head.repo.full_name}}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: LANGUAGE=go go test -v ./... -count 1

